repos:
  - repo: local
    hooks:
      - id: prevent-master-commit
        name: Prevent commits to master branch
        entry: bin/prevent-master-commit.sh
        language: system
        always_run: true
        pass_filenames: false